### ISSUE TITLE
Boot disk size

### ISSUE THREAD

**Issue by jsindy** [rimusz/glusterfs-gce#1]
By default the boot disk size is 200GB for the Gluster instance. I was curious if this is required? How much data is really stored outside of the bricks. Not saying it needs to be changed just curious.

**Comment by rimusz** [comment]
@jsindy you can have a smaller disk as well, but not too small as `glusterfs` server writes lots of logs to a disk

**Comment by jsindy** [comment]
Also noticed you get performance degradation under 200GB according to GCloud
