### ISSUE TITLE
Why does the glusterfs cluster require external ip addresses?

### ISSUE THREAD

**Issue by jsindy** [rimusz/glusterfs-gce#2]
It seem more secure if they only had internal address. I also noticed that currently create volume script requires these addresses.

When I remove the external address manually it seems to still function as expected just cant create new volumes.

**Comment by rimusz** [comment]
if you remove external IPs create volume script will not be able to access servers from your computer.
You can just block access to from internet and just whitelist your external IP, just a suggestion.
Or update `create volume script` to use internal IPs and put it on to one of servers and access the script form there.
