### ISSUE TITLE
create_cluster.sh script fails to install glusterfs-server

### ISSUE THREAD

**Issue by Locus99** [rimusz/glusterfs-gce#9]
Fails with the following error:
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 linux-libc-dev amd64 4.4.0-78.99
  404  Not Found [IP: 104.155.199.95 80]
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 linux-libc-dev amd64 4.4.0-78.99
  404  Not Found [IP: 104.155.199.95 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-78.99_amd64.deb  404  Not Found [IP: 104.155.199.95 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Was able to avoid error by running "sudo apt-get update command" before installing glusterfs-server

**Comment by rimusz** [comment]
thanks for reporting, added `sudo apt-get update` to `create_cluster.sh`
